name: clang-tidy-review
on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: ZedThree/clang-tidy-review@v0.14.0
      id: review
      with:
        cmake_command: 'cmake -S . -B build -DCMAKE_EXPORT_COMPILE_COMMANDS=on'
        build_dir: 'build'
        config_file: '.clang-tidy'
        exclude: 'chuffed/vars/int-var-*.h,thirdparty/**'
        apt_packages: 'zlib1g-dev'
        split_workflow: true
    - uses: ZedThree/clang-tidy-review/upload@v0.14.0
